apiVersion: apps/v1
kind: Deployment
metadata:
  name: auction-deployment
  labels:
    app: auction
spec:
  replicas: 1  # 변경 가능: 원하는 파드 수
  selector:
    matchLabels:
      app: auction
  template:
    metadata:
      labels:
        app: auction
    spec:
      containers:
      - name: auction
        image: leeinhong9512/panda-auction:c4464e401abe0b0dd313e01347eb45046a15b28c
        ports:
        - containerPort: 8081  # 애플리케이션이 사용하는 포트
        volumeMounts:
        - name: tz-seoul
          mountPath: /etc/localtime
        - name: auction-storage
          mountPath: /app  # PVC를 마운트할 경로
      volumes:
      - name: tz-seoul
        hostPath:
          path: /usr/share/zoneinfo/Asia/Seoul
      - name: auction-storage
        persistentVolumeClaim:
          claimName: auction-pvc  # PVC 이름
      nodeSelector:
        worker: was  # 노드 셀렉터 추가
        



---

apiVersion: v1
kind: Service
metadata:
  name: auction-service
spec:
  selector:
    app: auction
  ports:
    - protocol: TCP
      port: 8081  # 서비스에 노출되는 포트
      targetPort: 8081  # 파드에 포워딩되는 포트
      nodePort: 31000  # 변경 가능: 노드 포트 번호 (30000 ~ 32767 사이의 값을 선택)
  type: NodePort  # 서비스 유형을 NodePort로 변경
